apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::610739101347:role/EksClusterStackV6-ClusterAdminRoleV64C1FAFAE-nV69KmbzJovy
      username: arn:aws:iam::610739101347:role/EksClusterStackV6-ClusterAdminRoleV64C1FAFAE-nV69KmbzJovy
      groups:
        - system:masters
    - rolearn: arn:aws:iam::610739101347:role/EksClusterStackV6-NodeGroupRoleV6E51D8FA1-0ZLj7SrjIATC
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::610739101347:user/cdk-deployer-eks
      username: admin-user
      groups:
        - system:masters
  mapAccounts: "[]"